name: Checks

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master", "beta" ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Turbo
      run: npm install turbo --global
    - name: Install
      run: yarn install
    - name: Build-Lint
      run: turbo build lint

  Windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Turbo
      run: npm install turbo --global
    - name: Install
      run: yarn install
    - name: Build-Lint
      run: turbo build lint
